- name: FlagLagBot Provision
  hosts: localhost
  connection: local
  tasks:
  - name: Install boto
    sudo: yes
    pip: name=boto

  - name: create ec2 group
    ec2_group:
      name: webserver
      description: an EC2 webserver group
      region: us-east-1
      aws_access_key: AKIAITSZSL57S64MZSLQ
      aws_secret_key: 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
      state: present
      rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
      rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0


  - name: Create ec2 instance
    ec2: 
     aws_access_key: AKIAITSZSL57S64MZSLQ
     aws_secret_key: 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
     key_name: featureBot
     instance_type: t2.micro
     region: us-east-1
     image: ami-c8580bdf
     wait: yes
     group: webserver
     vpc_subnet_id: subnet-0dd85455
     assign_public_ip: yes
     wait_timeout: 600
     count: 1
     instance_tags:
      Name: "featureBot"
    register: ec2_instances


  - name: Add host to in-memory inventory
    add_host:
     hostname: "{{ec2_instances.instances[0].public_ip}}"
     groupname: ec2_host
     ansible_ssh_user: ubuntu
     ansible_ssh_private_key_file: ./featureBot.pem

  - name: Wait for SSH
    wait_for: 
     host: "{{ec2_instances.instances[0].public_ip}}"
     port: 22
     delay: 60
     state: started


- name: Setup
  hosts: ec2_host
  sudo: yes
  gather_facts: True
  user: root
  
  vars:
   - home_dir: /home/ubuntu
   - app_dir: App
   - temp_dir: /tmp/

  tasks:
  
   - name: Hello
     shell: echo Hello!
  
  
   - name: Install Packages 
     apt: name={{ item }} update_cache=yes  
     with_items:
       #- nodejs-legacy
       #- npm
       - git
     #shell: apt-get install nodejs && apt-get install npm && apt-get install git

   - name: Install Node
     shell: curl -sL https://deb.nodesource.com/setup_7.x | sudo -E bash - && apt-get install -y nodejs


   - name: Clone git repo 
     git: 
      repo: https://github.com/VivekBhat/FlagLagBot.git 
      dest: "{{home_dir}}/{{app_dir}}"
      clone: yes
     register: git_cloned

   - name: Install npm packages 
     npm:
      path: "{{home_dir}}/{{app_dir}}"
     
     
- name: Tasks 
  hosts: ec2_host
  sudo: yes

  vars:
   - home_dir: /home/ubuntu
   - app_dir: App
   - temp_dir: /tmp/

  tasks:
   - name: Run webserver
     command: node "{{home_dir}}/{{app_dir}}/server/server.js" 40676

   - name: Print All EC2 variables
     debug: var=ec2_host
